[package]
name = "toy8_telnet_mccp"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
default = []
real_mccp = ["flate2"]

[dependencies]

[dependencies.flate2]
version = "1.0"
optional = true
